name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npx tsc --project tests/tsconfig.json --noEmit
      - run: npx tsc --project examples/tsconfig.json --noEmit
      - run: npx tsc --project src/keyboard-engine/tests/tsconfig.json --noEmit
      - run: npx tsc --project packages/editor/tests/tsconfig.json --noEmit
      - run: npx tsc --project packages/i18n/tests/tsconfig.json --noEmit
      - run: npx tsc --project packages/theme/tests/tsconfig.json --noEmit
      - run: npx tsc --project packages/event/tests/tsconfig.json --noEmit

      - run: npx vitest run --coverage

  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run bench
        continue-on-error: true
